name: Gatling Maven Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "12 12 * * *"

jobs:
  Performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Build with Maven
        run: mvn gatling:verify

      - name: Run Gatling tests
        run: mvn gatling:test -Dgatling.simulationClass="com.gatling.demo.api.CrudApiTest" -Dgatling.directory="target/gatling/crudapitest-report"

      - name: Publish report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          publish_dir: ./target/gatling/crudapitest-report
